server:
  port: 8040

spring:
  application:
    name: gatway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启gatway 服务注册和发现
          low-case-service-id: true  #请求路径上的服务名配置为小写
      enabled: true #是否开启网关，默认开启
      routes:
      - id: route1
        uri: http://localhost:8021/
        #uri: lb://client
        predicates:
        #- Path=/api/**
        - Weight=group1, 5  #权重
        #filters:
       # - StripPrefix=1   #去掉前缀 数字大小表示去掉多少个前缀
      - id: route2
        uri: http://localhost:8020/
        #uri: lb://client
        predicates:
        - Weight=group1, 5
        #filters:
       # - StripPrefix=1   #去掉前缀 数字大小表示去掉多少个前缀

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
