server:
  port: 8040

spring:
  application:
    name: gatway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启gatway 服务注册和发现
          low-case-service-id: true  #请求路径上的服务名配置为小写
      enabled: true #是否开启网关，默认开启
      routes:
      - id: route1
        uri: http://localhost:8030/
        #uri: lb://client
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1   #去掉前缀 数字大小表示去掉多少个前缀

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.10.128:8761/eureka/
