server:
  port: 8021
spring:
  application:
    name: server

eureka:
  client:
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://192.168.10.104:8761/eureka/
### 重点
  instance:
      hostname: server
      prefer-ip-address: true

