server:
  port: 8761
spring:
  application:
    name: ek
eureka:
  client:
    #不注册自己的信息以供其他服务发现
    register-with-eureka: false
  instance:
    appname: ek
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 5
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000