server:
  port: 8030

spring:
  application:
    name: client
  cloud:
    #为了保持向后兼容性，使用作为默认的负载平衡器实现。但是，Spring Cloud Netflix Ribbon现在处于维护模式，所以我们建议使用Spring Cloud load均衡器。为此，设置spring.cloud.loadbalance .ribbon的值。使为false。
    loadbalancer:
      ribbon:
        enabled: false
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
sample-client:
  ribbon:
    #服务地址
    listOfServers: localhost:8020,localhost:8021
    #ribbon规则：RoundRobinRule（轮询）；RandomRule（随机）
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule